version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s %(name)s  %(levelname)s  %(message)s"
    datefmt: "%d-%m-%Y:%H:%M:%S"
  debug:
    # format: "%(asctime)s %(levelname)s <PID %(process)d:%(processName)s>: %(module)s.%(name)s.%(funcName)s():%(lineno)d: %(message)s"
    format: "%(asctime)s %(levelname)s %(name)s.%(funcName)s():%(lineno)d: %(message)s"
    datefmt: "%d-%m-%Y:%H:%M:%S"
  error:
    format: "%(asctime)s %(levelname)s %(module)s.%(name)s.%(funcName)s():%(lineno)d: %(message)s"
    datefmt: "%d-%m-%Y:%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: debug
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: logs/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: debug
    filename: logs/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  critical_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: standard
    filename: logs/critical.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  warn_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: standard
    filename: logs/warn.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: DEBUG
  handlers: [ console ]
  propogate: yes

loggers:
  __main__:
    level: INFO
    #handlers: [ info_file_handler, error_file_handler, debug_file_handler ]
    handlers: [ console ]
    propogate: yes
